sonar.projectKey=skypaw_czyjesthandlowa
sonar.organization=skypaw
sonar.projectName=czyjesthandlowa
sonar.python.version=3.12
sonar.coverage.exclusions=tests/*, scripts/sunday_subpages.py
sonar.python.coverage.reportPaths=coverage.xml
