domain: czyjesthandlowa.pl       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://czyjesthandlowa.pl  # the base hostname and protocol for your site, e.g. http://example.com
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "navbar"
