on:
  workflow_dispatch

jobs:
  upload-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: 'Use gcloud CLI'
      run: |
        curl -X PUT -H "Authorization: Bearer $(gcloud auth print-identity-token)" \
          https://www.googleapis.com/webmasters/v3/sites/czyjesthandlowa.pl/sitemaps/czyjesthandlowa.pl/sitemap.xml

